name: Build Docker Image and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout master'
      uses: actions/checkout@v2

    - name: 'Sign in to Azure'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
 
    - name: 'Build & Push to ACR'
      uses: azure/docker-login@v1
      with:
       login-server: acrhellofinal.azurecr.io
       username: ${{ secrets.REGISTRY_USERNAME }}
       password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - run: |
       docker build . -t acrhellofinal.azurecr.io/hellofinal:${{ github.sha }}
       docker push acrhellofinal.azurecr.io/hellofinal:${{ github.sha }}
 
    - name: 'Deploy from ACR to App Service'
      uses: azure/webapps-deploy@v2
      with:
       app-name: 'as-hello-final-10651055'
       images: 'acrhellofinal.azurecr.io/hellofinal:${{ github.sha }}'
    - run: |
       az logout
